### ISSUE TITLE
hoogle Eq a => ... fails

### ISSUE THREAD

**Issue by mbenke** [carlosgaldino/alfred-hoogle-workflow#2]
Trying to run an example from the readme (Eq a => ...) seems to derail this workflow at the arrow.

I have put the debug output at https://gist.github.com/mbenke/11077853 but essence of the error is

[ERROR: alfred.workflow.input.scriptfilter] XML Parse Error 'The operation couldn’t be completed. (NSXMLParserErrorDomain error 76.)'. Row (null), Col (null): '(null)' 

followed by repeated occurrences of

[ERROR: alfred.workflow.input.scriptfilter] Code 1: script.rb:18:in `<main>': undefined method`map' for nil:NilClass (NoMethodError)

**Comment by carlosgaldino** [comment]
The thing is that the query `(Eq a => )` doesn't work on Hoogle. Check it [here](http://www.haskell.org/hoogle/?hoogle=Eq+a+%3D%3E).

So that's why you get the errors. Try `Eq a => [a] -> [a]`, the complete version of the query used in the screenshot and see if it works.

I will close this but if it doesn't work reopen this issue and I will see what I can do.

Thanks.
